import { type EmrApiConfigurationResponse } from '@openmrs/esm-ward-app/src/hooks/useEmrConfiguration';

export const emrConfigurationMock: EmrApiConfigurationResponse = {
  clinicianEncounterRole: { uuid: '240b26f9-dd88-4172-823d-4a8bfeb7841f' },
  consultFreeTextCommentsConcept: { uuid: '162169AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' },
  visitNoteEncounterType: { uuid: 'd7151f82-c1f3-4152-a605-2f9ea7414a79' },
  admissionEncounterType: { uuid: 'e8151f82-c1f3-4152-a605-2f9ea7414a79' },
  inpatientNoteEncounterType: { uuid: 'f8151f82-c1f3-4152-a605-2f9ea7414a79' },
  transferRequestEncounterType: { uuid: 'g8151f82-c1f3-4152-a605-2f9ea7414a79' },
  supportsTransferLocationTag: { uuid: 'h8151f82-c1f3-4152-a605-2f9ea7414a79', name: 'Transfer Location' },
  supportsAdmissionLocationTag: { uuid: 'i8151f82-c1f3-4152-a605-2f9ea7414a79', name: 'Admission Location' },
  dispositionDescriptor: {
    admissionLocationConcept: { uuid: 'admission-location-concept-uuid' },
    dateOfDeathConcept: { uuid: 'date-of-death-concept-uuid' },
    dispositionConcept: { uuid: 'disposition-concept-uuid' },
    internalTransferLocationConcept: { uuid: 'internal-transfer-location-concept-uuid' },
    dispositionSetConcept: { uuid: 'disposition-set-concept-uuid' },
  },
  dispositions: [
    {
      uuid: 'admit-disposition-uuid',
      name: 'Admit to hospital',
      conceptCode: 'PIH:ADMIT TO HOSPITAL',
      type: 'ADMIT',
      encounterTypes: null,
      keepsVisitOpen: null,
      additionalObs: null,
      careSettingTypes: ['OUTPATIENT'],
      actions: [],
      excludedEncounterTypes: [],
    },
    {
      uuid: 'transfer-disposition-uuid',
      name: 'Transfer to location',
      conceptCode: 'PIH:TRANSFER OUT OF HOSPITAL',
      type: 'TRANSFER',
      encounterTypes: null,
      keepsVisitOpen: null,
      additionalObs: null,
      careSettingTypes: ['OUTPATIENT'],
      actions: [],
      excludedEncounterTypes: [],
    },
  ],
};
