import * as Yup from 'yup';
import React, { useState, useEffect, useCallback, useMemo } from 'react';
import find from 'lodash-es/find';
import styles from '../../input.scss';
import { useField } from 'formik';
import { useTranslation } from 'react-i18next';
import { SelectInput } from '../../basic-input/select/select-input.component';
import { Input } from '../../basic-input/input/input.component';
import { CustomPatientIdentifierType, PatientIdentifierType } from '../../../patient-registration-types';
import { PatientRegistrationContext } from '../../../patient-registration-context';
import { TrashCan16 } from '@carbon/icons-react';
import { Button } from 'carbon-components-react';

interface IdentifierInputProps {
  identifierType: CustomPatientIdentifierType;
}

export const IdentifierInput: React.FC<IdentifierInputProps> = ({ identifierType }) => {
  const { validationSchema, setValidationSchema, setFieldValue, setPatientIdentifiers } =
    React.useContext(PatientRegistrationContext);
  const source = identifierType.selectedSource;
  const name = identifierType.fieldName;
  const { t } = useTranslation();
  const [option, setAutoGenerationOption] = useState({
    manualEntryEnabled: source ? true : undefined,
    automaticGenerationEnabled: undefined,
  });
  const [identifierValidationSchema, setIdentifierValidationSchema] = useState(Yup.object({}));

  useEffect(() => {
    if (source && source.autoGenerationOption && source.autoGenerationOption.automaticGenerationEnabled) {
      identifierType.autoGenerationSource = source;
    }
  }, [source]);

  useEffect(() => {
    let validatorProps = Yup.string();
    validatorProps = validatorProps.required("Identifier can't be blank!");

    if (identifierType.format) {
      validatorProps = validatorProps.matches(new RegExp(identifierType.format), 'Invalid identifier format!');
    }

    const schemaBuilder = {};
    schemaBuilder[identifierType.fieldName] = validatorProps;
    identifierValidationSchema[identifierType.fieldName] = validatorProps;
    setIdentifierValidationSchema(Yup.object(schemaBuilder));
  }, []);

  useEffect(() => {
    if (source) {
      if (source.autoGenerationOption) {
        setAutoGenerationOption(source.autoGenerationOption);

        if (source.autoGenerationOption.automaticGenerationEnabled) {
          setPatientIdentifiers((identifiers) =>
            identifiers.map((identifier) =>
              identifier?.uuid === identifierType?.uuid
                ? {
                    ...identifierType,
                    autoGenerationSource: source,
                  }
                : identifier,
            ),
          );
          setFieldValue(name, '');

          if (validationSchema.fields[identifierType.fieldName]) {
            validationSchema.fields[identifierType.fieldName] = Yup.string();
          }
        } else {
          setValidationSchema(validationSchema.concat(identifierValidationSchema));
        }
      } else {
        setValidationSchema(validationSchema.concat(identifierValidationSchema));
        setAutoGenerationOption({
          manualEntryEnabled: true,
          automaticGenerationEnabled: false,
        });
      }
    } else {
      setValidationSchema(validationSchema.concat(identifierValidationSchema));
      setAutoGenerationOption({
        manualEntryEnabled: true,
        automaticGenerationEnabled: false,
      });
    }
  }, [source]);

  const handleDelete = useCallback(() => {
    setPatientIdentifiers((identifiers) =>
      identifiers.map((identifier) =>
        identifier?.uuid === identifierType?.uuid
          ? {
              ...identifierType,
              selected: false,
              selectedSource: null,
            }
          : identifier,
      ),
    );
  }, [identifierType]);

  const autoGenerated = !option.manualEntryEnabled || (option.manualEntryEnabled && option.automaticGenerationEnabled);

  return (
    <div className={styles.IDInput}>
      {option.manualEntryEnabled ? (
        <Input
          id={name}
          light
          placeholder={
            autoGenerated
              ? `${t('autoGeneratedPlaceholderText', 'Auto generated')}`
              : `${t('enterIdentifierPlaceholderText', 'Enter Identifier')}`
          }
          labelText={`${identifierType?.name}${
            autoGenerated ? `(${t('autoGeneratedPlaceholderText', 'Auto generated')})` : ''
          }`}
          name={name}
          disabled={!option.manualEntryEnabled}
        />
      ) : (
        <div className={styles.textID}>
          <p className={styles.label}>{`${identifierType?.name}`}</p>
          <p className={styles.bodyShort02}>{t('autoGeneratedPlaceholderText', 'Auto generated')}</p>
        </div>
      )}
      {!identifierType?.isPrimary && (
        <Button kind="ghost" onClick={handleDelete} iconDescription={t('deleteID', 'Delete ID')} hasIconOnly>
          <TrashCan16 className={styles.trashCan} />
        </Button>
      )}
    </div>
  );
};
