import React, { useContext, useMemo } from 'react';
import { IdentifierInput } from '../../input/custom-input/identifier/identifier-input.component';
import { IdentifierSource } from '../../patient-registration-types';
import styles from '../field.scss';
import { useTranslation } from 'react-i18next';
import { PatientRegistrationContext } from '../../patient-registration-context';

function containsSourceWithAnOption(sources: Array<IdentifierSource>): boolean {
  for (const source of sources) {
    if (source.autoGenerationOption) {
      return true;
    }
  }

  return false;
}

export const IdField: React.FC = () => {
  const { identifierTypes, inEditMode, values, showPatientIdentifiersOverlay, patientIdentifiersMap } =
    useContext(PatientRegistrationContext);
  const { t } = useTranslation();

  const identifierInputs = useMemo(
    () =>
      identifierTypes
        .filter((identifierType) => patientIdentifiersMap[identifierType.uuid].selected)
        .map((identifierType) => {
          console.log(values?.identifiers, identifierType.fieldName);
          const sources = identifierType.identifierSources;
          const hasSourcesButWithoutOptions = sources.length > 0 && !containsSourceWithAnOption(sources);
          const mayOnlySupportAuto =
            sources.length == 1
              ? sources[0].autoGenerationOption
                ? !sources[0].autoGenerationOption.manualEntryEnabled
                : true
              : false;

          if (inEditMode && values.identifiers[identifierType.fieldName]) {
            console.log(1);
            return (
              <div key={identifierType.fieldName}>
                <IdentifierInput key={identifierType.fieldName} identifierType={identifierType} disabled />
              </div>
            );
          } else if (hasSourcesButWithoutOptions || mayOnlySupportAuto) {
            // identifier will be autogenerated
            identifierType.autoGenerationSource = identifierType.identifierSources[0];
            console.log(2);
            return null;
          } else {
            return <IdentifierInput key={identifierType.fieldName} identifierType={identifierType} />;
          }
        }),
    [patientIdentifiersMap, values.identifiers],
  );

  return (
    <div>
      <h4 className={styles.productiveHeading02Light}>{t('idFieldLabelText', 'Id')}</h4>
      <div className={styles.grid}>
        {identifierInputs}
        <span
          className={`${styles.bodyShort01} ${styles.linkText} ${styles.addNewIdentifierButton}`}
          onClick={() => showPatientIdentifiersOverlay(true)}
          role="button"
          tabIndex={0}>
          {t('addIDNumber', 'Add ID number')} +
        </span>
      </div>
    </div>
  );
};
