name: Report bundle size

on:
  pull_request_target:
    branches: [main]

jobs:
  file_size_impact:
    runs-on: ubuntu-latest

    steps:
      - name: Setup git
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          check-latest: true
      - run: npx lerna bootstrap
      - name: Report changes
        run: node ./tools/size-reporter.mjs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
